version: "3"

services:

  virtuoso:
    container_name: shapes-of-you-virtuoso
    image: tenforce/virtuoso:latest
    # image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    restart: unless-stopped
    volumes:
      - /data/shapes-of-you/virtuoso:/data
    environment:
      # Deployed using https://github.com/nginx-proxy
      - VIRTUAL_HOST=${VIRTUOSO_URL}
      - LETSENCRYPT_HOST=${VIRTUOSO_URL}
      - VIRTUAL_PORT=8890
      # http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning
      # http://docs.openlinksw.com/virtuoso/rdfperfgeneral/
      - DBA_PASSWORD=${VIRTUOSO_PASSWORD}
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=https://w3id.org/um/shapes-of-you
      - VIRT_Parameters_DirsAllowed=., /data, /usr/local/virtuoso-opensource/share/virtuoso/vad, /usr/local/virtuoso-opensource/var/lib/virtuoso/db
      - VIRT_Database_ErrorLogLevel=1 # default: 7 is maximum logs
      # Bio2RDF large dataset config
      - VIRT_SPARQL_MaxQueryCostEstimationTime=200000
      - VIRT_SPARQL_MaxQueryExecutionTime=1000000
      - VIRT_Database_MaxCheckpointRemap=125000
      - VIRT_TempDatabase_MaxCheckpointRemap=125000
      - VIRT_Parameters_TempDBSize=100000000
      - VIRT_Parameters_NumberOfBuffers=5450000 # For 64G systems
      - VIRT_Parameters_MaxDirtyBuffers=4000000
      # - VIRT_Parameters_NumberOfBuffers=10880000 # For 128G systems
      # - VIRT_Parameters_MaxDirtyBuffers=8000000
      - VIRT_SPARQL_ShortenLongURIs=1
      - VIRT_SPARQL_MaxCacheExpiration=1
      - VIRT_SPARQL_ExternalQuerySource=1
      - VIRT_SPARQL_ExternalXsltSource=1
    # ports:
    #   - 8890:8890

  # webapp:
  #   build: .
  #   container_name: projects
  #   ports:
  #     - 5000:5000