version: "3"

services:

  virtuoso:
    container_name: shapes-of-you-virtuoso
    image: tenforce/virtuoso:latest
    # image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    restart: unless-stopped
    volumes:
      - /data/shapes-of-you/virtuoso:/data
    environment:
      # Deployed using https://github.com/nginx-proxy
      - VIRTUAL_HOST=${VIRTUOSO_URL}
      - LETSENCRYPT_HOST=${VIRTUOSO_URL}
      - VIRTUAL_PORT=8890
      # http://vos.openlinksw.com/owiki/wiki/VOS/VirtRDFPerformanceTuning
      # http://docs.openlinksw.com/virtuoso/rdfperfgeneral/
      - DBA_PASSWORD=${VIRTUOSO_PASSWORD}
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=http://bio2rdf.org
      - VIRT_Parameters_DirsAllowed=., /data, /usr/local/virtuoso-opensource/share/virtuoso/vad, /usr/local/virtuoso-opensource/var/lib/virtuoso/db
      - VIRT_SPARQL_ResultSetMaxRows=999999999999999999
      - VIRT_SPARQL_MaxQueryCostEstimationTime=100000
      - VIRT_SPARQL_MaxQueryExecutionTime=6000
      - VIRT_VDB_VDBDisconnectTimeout=7200000
      - VIRT_Client_SQL_QUERY_TIMEOUT=14400000
      - VIRT_CLient_SQL_TXN_TIMEOUT=14400000
      - VIRT_Database_ErrorLogLevel=0 # default: 7 is maximum logs
      - VIRT_Parameters_Timeout=7200
      - VIRT_Parameters_TransactionAfterImageLimit=5000000000 # default is 50M
      - VIRT_Parameters_NumberOfBuffers=493674 # To use up to 4G of RAM according to documentation
      # Each buffer caches one 8K page of data and occupies approximately 8700 bytes of memory.
      # - VIRT_Parameters_NumberOfBuffers=680000 # For 16G systems according to Optimization docs, but cause freeze
      # - VIRT_Parameters_MaxDirtyBuffers=500000
      # - VIRT_Parameters_NumberOfBuffers=5450000 # For 64G systems
      # - VIRT_Parameters_MaxDirtyBuffers=4000000
      # - VIRT_Parameters_MaxCheckpointRemap=4000
      # - VIRT_Parameters_MaxClientConnections= 10 # Better to reduce if a lot of big requests
      # - VIRT_SPARQL_DefaultQuery=select distinct ?Concept where {[] a ?Concept} LIMIT 100
      # - VIRT_VDB_VDBDisconnectTimeout=7200000
      # - VIRT_Client_SQL_QUERY_TIMEOUT=14400000
      # - VIRT_CLient_SQL_TXN_TIMEOUT=14400000
      # Opt in GB
      # $buffers = floor($opt * 85000);
      # $dirtybuffers = floor($opt * 62500);
    # ports:
    #   - 8890:8890

  # webapp:
  #   build: .
  #   container_name: projects
  #   ports:
  #     - 5000:5000