name: Get shapes from GitHub GraphQL API
on:
  workflow_dispatch:
    inputs:
      clear:
        description: 'Clear the Shapes triplestore'
        required: true
        default: 'false'
  schedule:
    # Everyday at 01:00 and 13:00
    - cron:  '00 01,13 * * *'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/get-shapes-github.yml'
    - 'get_github_data/*'
    - 'EXTERNAL_REPOSITORIES.txt'

jobs:
  query-graphql-for-shapes:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    # Important part here (can be reused to run locally):
    - name: Install Python dependencies
      run: |
        python -m pip install -r get_github_data/requirements.txt

    - name: Query GitHub GraphQL API and populate triplestore with Python
      env:
        GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        SPARQL_PASSWORD: ${{ secrets.GRAPHDB_PASSWORD }}
      run: |-
        python get_github_data/get_shapes_from_github.py

    - name: Upload failed shapes report
      uses: actions/upload-artifact@v1
      with:
        name: failed-shapes-report
        path: FAILED_IMPORT_REPORT.md

    - name: Upload RDF output 
      uses: actions/upload-artifact@v1
      with:
        name: shapes-of-you-rdf
        path: shapes-of-you-rdf.ttl

    - name: Clear older graph in the triplestore
      if: github.event.inputs.clear == 'true'
      uses: vemonet/sparql-operations-action@v1
      with:
        query: "CLEAR GRAPH <https://w3id.org/um/ids/shapes>"
        endpoint: https://graphdb.dumontierlab.com/repositories/shapes-registry/statements
        user: ${{ secrets.GRAPHDB_USER }}
        password: ${{ secrets.GRAPHDB_PASSWORD }}

    - name: Upload the RDF to the triplestore
      uses: MaastrichtU-IDS/RdfUpload@master
      with:
        file: shapes-of-you-rdf.ttl
        endpoint: https://graphdb.dumontierlab.com/repositories/ids-projects/statements
        user: ${{ secrets.GRAPHDB_USER }}
        password: ${{ secrets.GRAPHDB_PASSWORD }}
        graph: "https://w3id.org/um/ids/projects/graph"

    # - uses: MaastrichtU-IDS/sparql-operations-action@v1
    #   with:
    #     operation: upload
    #     file: shapes-of-you-rdf.ttl
    #     endpoint: https://graphdb.dumontierlab.com/repositories/ids-projects/statements
    #     user: ${{ secrets.GRAPHDB_USER }}
    #     password: ${{ secrets.GRAPHDB_PASSWORD }}
    #     graph: "https://w3id.org/um/ids/projects/graph"
    #     # inputvar: https://w3id.org/d2s/graph/geonames
    #     # outputvar: https://w3id.org/d2s/metadata
    #     # servicevar: http://localhost:7200/repositories/test-vincent