name: Index shapes
on:
  schedule:
    # Everyday at 01:00 
    - cron:  '00 01 * * *'
  workflow_dispatch:
  #   inputs:
  #     clear:
  #       description: 'Clear the Shapes triplestore'
  #       required: true
  #       default: 'false'
  # push:
  #   branches: [ main ]
  #   paths:
  #   - '.github/workflows/get-shapes.yml'
  #   - 'etl/*'
  #   - 'EXTRAS_GITHUB_REPOSITORIES.txt'

jobs:
  query-git-services-for-shapes:
    strategy:
      fail-fast: false
      matrix:
        include:
        - git-service: github
          run-label: topics-w3c
          search-topics: topic:owl,topic:shacl-shapes,topic:shex,topic:grlc,topic:skos,topic:obofoundry
        - git-service: github
          run-label: topics-openapi
          search-topics: topic:openapi,topic:smartapi,topic:ncats-translator,topic:translator-api
        - git-service: github
          run-label: topics-api
          search-topics: topic:api
        - git-service: github
          run-label: rml-run
          search-topics: r2rml,rml,topic:rml-mapping
        - git-service: github-extras
          run-label: extra-1
          search-topics: EXTRAS_GITHUB_REPOSITORIES.txt
        - git-service: github-extras
          run-label: extra-2
          search-topics: EXTRAS_GITHUB_REPOSITORIES_2.txt
        - git-service: github
          run-label: direct-search-openapi
          search-topics: ncats+translator,biothings,smartapi,knowledge+provider
        - git-service: github
          run-label: direct-search-shacl
          search-topics: shacl
        - git-service: gitee
          run-label: ontology-run
          search-topics: ontology,sparql
        - git-service: gitee
          run-label: sparql-run
          search-topics: sparql
        - git-service: gitlab
          run-label: main-run
          search-topics: owl,shacl,shex,sparql,skos,obofoundry
        # - git-service: gitlab
        #   run-label: run-3
        #   search-topics: ontology # Fails without warnings

    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Python requirements
      run: |
        python -m pip install -r etl/requirements.txt
        sudo apt-get install libicu-dev python3-dev

    - name: Run Python script to index ${{ matrix.search-topics }} in ${{ matrix.git-service }}
      env:
        GIT_SERVICE: ${{ matrix.git-service }}
        SEARCH_TOPICS: ${{ matrix.search-topics }}
        API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
      run: |
        python etl/index_shapes.py $GIT_SERVICE $SEARCH_TOPICS

    - name: Upload failed shapes report as artifact
      uses: actions/upload-artifact@v1
      with:
        name: report-${{ matrix.git-service }}-${{ matrix.run-label }}
        path: REPORT.md

    - name: Commit and push report-${{ matrix.git-service }}-${{ matrix.run-label }}.md file in report branch
      env:
        GIT_SERVICE: ${{ matrix.git-service }}
        RUN_LABEL: ${{ matrix.run-label }}
      run: |
        mv REPORT.md tmp-REPORT.md
        git stash
        git fetch
        git checkout report
        mv tmp-REPORT.md report-$GIT_SERVICE-$RUN_LABEL.md
        git diff
        git config --global user.email "vincent.emonet@gmail.com"
        git config --global user.name "Vincent Emonet"
        git add report-$GIT_SERVICE-$RUN_LABEL.md
        git commit -m "Update report-$GIT_SERVICE-$RUN_LABEL.md" || exit 0
        git push || exit 0

    - name: Upload ${{ matrix.git-service }}-${{ matrix.run-label }} RDF output as artifact
      uses: actions/upload-artifact@v1
      with:
        name: shapes-rdf-${{ matrix.git-service }}-${{ matrix.run-label }}
        path: shapes-rdf.ttl

    - name: Upload ${{ matrix.git-service }}-${{ matrix.run-label }} RDF file to the triplestore
      uses: MaastrichtU-IDS/RdfUpload@master
      with:
        file: shapes-rdf.ttl
        endpoint: https://graphdb.dumontierlab.com/repositories/shapes-registry/statements
        user: ${{ secrets.GRAPHDB_USER }}
        password: ${{ secrets.GRAPHDB_PASSWORD }}
        graph: "https://w3id.org/um/ids/shapes/${{ matrix.git-service }}"


    # - name: Clear older graph in the triplestore
    #   if: github.event.inputs.clear == 'true'
    #   uses: vemonet/sparql-operations-action@v1
    #   with:
    #     query: "CLEAR GRAPH <https://w3id.org/um/ids/shapes>"
    #     endpoint: https://graphdb.dumontierlab.com/repositories/shapes-registry/statements
    #     user: ${{ secrets.GRAPHDB_USER }}
    #     password: ${{ secrets.GRAPHDB_PASSWORD }}

